// TEMPORARY DATA

export let role = "admin";

export const phoneCallLogData = [
  {
    id: 1,
    name: "Cleaning Services",
    phone: "905677846",
    date: "2025-06-26",
    description: "bhsbhdfj",
    nextFollowUpDate: "2025-06-30",
    duration: "45minutes",
    callType: "Outgoing",
    note: "jhdfgjdf",
  },
  {
    id: 2,
    name: "Telephone Office",
    phone: "809678546",
    date: "2025-06-25",
    nextFollowUpDate: "2025-06-28",
    callType: "Outgoing",
  },
  {
    id: 3,
    name: "Staff Health Checkup",
    phone: "980567453",
    date: "2025-06-20",
    nextFollowUpDate: "2025-06-23",
    callType: "Outgoing",
  },
  {
    id: 4,
    name: "Electricity Office",
    phone: "899056734",
    date: "2025-06-16",
    nextFollowUpDate: "2025-06-18",
    callType: "Incoming",
  },
  {
    id: 5,
    name: "New Book-Stock",
    phone: "9056734523",
    date: "2025-06-10",
    nextFollowUpDate: "2025-06-12",
    callType: "Outgoing",
  },
  {
    id: 6,
    name: "Parent Inquiry",
    phone: "8901234567",
    date: "2025-06-15",
    nextFollowUpDate: "2025-06-20",
    callType: "Incoming",
  },
  {
    id: 7,
    name: "School Transport Service",
    phone: "9102345678",
    date: "2025-06-18",
    nextFollowUpDate: "2025-06-21",
    callType: "Outgoing",
  },
  {
    id: 8,
    name: "Water Supply Department",
    phone: "9876543210",
    date: "2025-06-12",
    nextFollowUpDate: "2025-06-16",
    callType: "Incoming",
  },
  {
    id: 9,
    name: "School Uniform Supplier",
    phone: "9123456780",
    date: "2025-06-19",
    nextFollowUpDate: "2025-06-25",
    callType: "Outgoing",
  },
  {
    id: 10,
    name: "Library Vendor",
    phone: "9800001122",
    date: "2025-06-05",
    nextFollowUpDate: "2025-06-09",
    callType: "Outgoing",
  },
  {
    id: 11,
    name: "Event Management",
    phone: "9012345678",
    date: "2025-06-03",
    nextFollowUpDate: "2025-06-07",
    callType: "Outgoing",
  },
  {
    id: 12,
    name: "Maintenance Contractor",
    phone: "8901122334",
    date: "2025-06-08",
    nextFollowUpDate: "2025-06-11",
    callType: "Incoming",
  },
  {
    id: 13,
    name: "Photography Service",
    phone: "9112233445",
    date: "2025-06-14",
    nextFollowUpDate: "2025-06-18",
    callType: "Outgoing",
  },
  {
    id: 14,
    name: "Security Agency",
    phone: "9887766554",
    date: "2025-06-17",
    nextFollowUpDate: "2025-06-22",
    callType: "Outgoing",
  },
  {
    id: 15,
    name: "PTA Chairman",
    phone: "9234567890",
    date: "2025-06-01",
    nextFollowUpDate: "2025-06-05",
    callType: "Incoming",
  },
  {
    id: 16,
    name: "Stationery Supplier",
    phone: "9871122334",
    date: "2025-06-11",
    nextFollowUpDate: "2025-06-14",
    callType: "Outgoing",
  },
  {
    id: 17,
    name: "Furniture Vendor",
    phone: "9892233445",
    date: "2025-06-04",
    nextFollowUpDate: "2025-06-10",
    callType: "Outgoing",
  },
  {
    id: 18,
    name: "Software Support",
    phone: "9012233445",
    date: "2025-06-06",
    nextFollowUpDate: "2025-06-12",
    callType: "Incoming",
  },
  {
    id: 19,
    name: "Insurance Company",
    phone: "9113344556",
    date: "2025-06-09",
    nextFollowUpDate: "2025-06-15",
    callType: "Outgoing",
  },
  {
    id: 20,
    name: "Food Supplier",
    phone: "9124455667",
    date: "2025-06-13",
    nextFollowUpDate: "2025-06-19",
    callType: "Outgoing",
  },
];

export const visitorsData = [
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Ibrahim Musa",
    studentSession: "2024/2025",
    visitorName: "Mr. Adebayo Johnson",
    phone: "+2348012345678",
    idCard: "Driver's License",
    numberOfPersons: 1,
    date: "2025-06-01",
    inTime: "09:00",
    outTime: "10:00",
    attachments: ["passport_photo.jpg"],
    note: "Parent meeting about school fees",
  },
  {
    purpose: "PTA",
    meetingWith: "staff",
    staffName: "Mrs. Grace Olumide",
    visitorName: "Mrs. Chinelo Obi",
    phone: "+2348023456789",
    idCard: "National ID",
    numberOfPersons: 2,
    date: "2025-06-02",
    inTime: "10:30",
    outTime: "12:00",
    attachments: ["pta_invite.pdf"],
    note: "PTA executive visit",
  },
  {
    purpose: "staff meeting",
    meetingWith: "staff",
    staffName: "Mr. Usman Bello",
    visitorName: "Mr. Tunde Akande",
    phone: "+2348034567890",
    idCard: "International Passport",
    numberOfPersons: 1,
    date: "2025-06-03",
    inTime: "11:00",
    outTime: "11:45",
    attachments: ["staff_meeting_agenda.pdf"],
    note: "School maintenance proposal discussion",
  },
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Chinedu Okafor",
    studentSession: "2023/2024",
    visitorName: "Mrs. Esther Okafor",
    phone: "+2348045678901",
    idCard: "PVC",
    numberOfPersons: 1,
    date: "2025-06-04",
    inTime: "12:30",
    outTime: "13:15",
    attachments: [],
    note: "Guardian meeting for academic performance discussion",
  },
  {
    purpose: "staff meeting",
    meetingWith: "staff",
    staffName: "Mrs. Juliet Emeka",
    visitorName: "Mr. Ahmed Yusuf",
    phone: "+2348056789012",
    idCard: "Driver's License",
    numberOfPersons: 2,
    date: "2025-06-05",
    inTime: "08:45",
    outTime: "09:30",
    attachments: ["proposal.pdf"],
    note: "Uniform supplier meeting",
  },
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Fatima Sani",
    studentSession: "2025/2026",
    visitorName: "Mr. Abdul Sani",
    phone: "+2348067890123",
    idCard: "Voter's Card",
    numberOfPersons: 1,
    date: "2025-06-06",
    inTime: "14:00",
    outTime: "15:00",
    attachments: [],
    note: "Medical leave discussion",
  },
  {
    purpose: "PTA",
    meetingWith: "staff",
    staffName: "Mr. Peter Ayodele",
    visitorName: "Mrs. Folake Ayodele",
    phone: "+2348078901234",
    idCard: "National ID",
    numberOfPersons: 3,
    date: "2025-06-07",
    inTime: "09:30",
    outTime: "11:00",
    attachments: ["pta_minute.pdf"],
    note: "PTA end-of-term planning",
  },
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Blessing Edet",
    studentSession: "2022/2023",
    visitorName: "Mrs. Ijeoma Edet",
    phone: "+2348089012345",
    idCard: "Driver's License",
    numberOfPersons: 1,
    date: "2025-06-08",
    inTime: "12:00",
    outTime: "12:45",
    attachments: [],
    note: "Discussing child’s classroom behavior",
  },
  {
    purpose: "staff meeting",
    meetingWith: "staff",
    staffName: "Mr. Nnamdi Okoro",
    visitorName: "Engr. Patrick Uche",
    phone: "+2348090123456",
    idCard: "International Passport",
    numberOfPersons: 2,
    date: "2025-06-09",
    inTime: "10:00",
    outTime: "11:00",
    attachments: ["engineering_plan.pdf"],
    note: "Proposing ICT lab installation",
  },
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Emmanuel Chukwu",
    studentSession: "2021/2022",
    visitorName: "Mr. Dominic Chukwu",
    phone: "+2348101234567",
    idCard: "PVC",
    numberOfPersons: 1,
    date: "2025-06-10",
    inTime: "09:00",
    outTime: "10:15",
    attachments: [],
    note: "Requested scholarship verification",
  },
  {
    purpose: "PTA",
    meetingWith: "staff",
    staffName: "Mrs. Ronke Afolabi",
    visitorName: "Mrs. Bisi Adeola",
    phone: "+2348112345678",
    idCard: "National ID",
    numberOfPersons: 1,
    date: "2025-06-11",
    inTime: "13:00",
    outTime: "14:00",
    attachments: ["pta_invitation.pdf"],
    note: "Volunteer for PTA event coordination",
  },
  {
    purpose: "staff meeting",
    meetingWith: "staff",
    staffName: "Mr. Kunle Ade",
    visitorName: "Mr. Adamu Gana",
    phone: "+2348123456789",
    idCard: "Driver's License",
    numberOfPersons: 2,
    date: "2025-06-12",
    inTime: "11:45",
    outTime: "12:30",
    attachments: [],
    note: "Maintenance issue resolution",
  },
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Ngozi Okoro",
    studentSession: "2020/2021",
    visitorName: "Mrs. Felicia Okoro",
    phone: "+2348134567890",
    idCard: "PVC",
    numberOfPersons: 1,
    date: "2025-06-13",
    inTime: "12:15",
    outTime: "13:00",
    attachments: [],
    note: "Complaint about class results",
  },
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Abdulahi Musa",
    studentSession: "2026/2027",
    visitorName: "Mrs. Aminat Musa",
    phone: "+2348145678901",
    idCard: "National ID",
    numberOfPersons: 2,
    date: "2025-06-14",
    inTime: "10:30",
    outTime: "11:45",
    attachments: ["birth_certificate.pdf"],
    note: "Admission clarification visit",
  },
  {
    purpose: "staff meeting",
    meetingWith: "staff",
    staffName: "Mr. Sunday Adebisi",
    visitorName: "Mr. Femi Adewole",
    phone: "+2348156789012",
    idCard: "International Passport",
    numberOfPersons: 1,
    date: "2025-06-15",
    inTime: "09:30",
    outTime: "10:15",
    attachments: [],
    note: "Catering services proposal",
  },
  {
    purpose: "PTA",
    meetingWith: "staff",
    staffName: "Mrs. Nkechi Umeh",
    visitorName: "Mrs. Clara Iroha",
    phone: "+2348167890123",
    idCard: "Driver's License",
    numberOfPersons: 1,
    date: "2025-06-16",
    inTime: "14:00",
    outTime: "15:00",
    attachments: [],
    note: "PTA treasurer follow-up meeting",
  },
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Kingsley Eze",
    studentSession: "2027/2028",
    visitorName: "Mr. Gabriel Eze",
    phone: "+2348178901234",
    idCard: "PVC",
    numberOfPersons: 1,
    date: "2025-06-17",
    inTime: "08:00",
    outTime: "09:00",
    attachments: [],
    note: "Requesting leave of absence",
  },
  {
    purpose: "staff meeting",
    meetingWith: "staff",
    staffName: "Mrs. Janet Abiola",
    visitorName: "Mrs. Lydia Ogundele",
    phone: "+2348189012345",
    idCard: "National ID",
    numberOfPersons: 2,
    date: "2025-06-18",
    inTime: "13:30",
    outTime: "14:30",
    attachments: [],
    note: "Event hall rental negotiation",
  },
  {
    purpose: "student meeting",
    meetingWith: "student",
    studentName: "Hassan Suleiman",
    studentSession: "2019/2020",
    visitorName: "Mr. Suleiman Bello",
    phone: "+2348190123456",
    idCard: "Driver's License",
    numberOfPersons: 1,
    date: "2025-06-19",
    inTime: "11:30",
    outTime: "12:30",
    attachments: ["school_id_card.png"],
    note: "Requested refund of school fee",
  },
  {
    purpose: "staff meeting",
    meetingWith: "staff",
    staffName: "Mr. Emeka Ezeugo",
    visitorName: "Mrs. Nkiru Ezeugo",
    phone: "+2348201234567",
    idCard: "PVC",
    numberOfPersons: 1,
    date: "2025-06-20",
    inTime: "09:45",
    outTime: "10:30",
    attachments: [],
    note: "PTA financial records review",
  },
];

export const postalDispatchData = [
  {
    toTitle: "Principal, Lagos High School",
    referenceNo: "PD-2025-001",
    address: "12, Broad Street, Lagos Island",
    note: "Official invitation to Annual Conference",
    fromTitle: "Admin Office",
    date: "2025-06-01",
    attachments: ["/attachments/invitation.jpg"],
  },
  {
    toTitle: "Registrar, State Education Board",
    referenceNo: "PD-2025-002",
    address: "22, Adeola Odeku Street, Victoria Island",
    note: "Request for student enrollment statistics",
    fromTitle: "Academic Affairs",
    date: "2025-06-02",
    attachments: ["/attachments/enrollment.jpg"],
  },
  {
    toTitle: "CEO, Book Suppliers Ltd.",
    referenceNo: "PD-2025-003",
    address: "Plot 5, Ajah Industrial Estate, Lekki",
    note: "Order for new textbooks for 2025 session",
    fromTitle: "Procurement Unit",
    date: "2025-06-03",
    attachments: ["/attachments/book-order.jpg"],
  },
  {
    toTitle: "Director, WAEC Office",
    referenceNo: "PD-2025-004",
    address: "WAEC Office, Yaba, Lagos",
    note: "Submission of examination registration forms",
    fromTitle: "Exams Office",
    date: "2025-06-04",
    attachments: ["/attachments/registration.jpg"],
  },
  {
    toTitle: "Manager, Cleaning Services Co.",
    referenceNo: "PD-2025-005",
    address: "14, Awolowo Way, Ikeja",
    note: "Renewal of contract for cleaning services",
    fromTitle: "Facility Management",
    date: "2025-06-05",
    attachments: ["/attachments/contract.jpg"],
  },
  {
    toTitle: "PTA Chairman",
    referenceNo: "PD-2025-006",
    address: "PTA Office, School Premises",
    note: "Notification of upcoming PTA meeting",
    fromTitle: "School Management",
    date: "2025-06-06",
    attachments: ["/attachments/pta-notice.jpg"],
  },
  {
    toTitle: "ICT Support Partner",
    referenceNo: "PD-2025-007",
    address: "Tech Park, Abuja",
    note: "Complaint about server downtime",
    fromTitle: "ICT Department",
    date: "2025-06-07",
    attachments: ["/attachments/server-issue.jpg"],
  },
  {
    toTitle: "Supplier, Sports Equipment Ltd.",
    referenceNo: "PD-2025-008",
    address: "10, Glover Road, Ikoyi",
    note: "Quotation request for sports kits",
    fromTitle: "Sports Unit",
    date: "2025-06-08",
    attachments: ["/attachments/sports-quote.jpg"],
  },
  {
    toTitle: "Ministry of Health",
    referenceNo: "PD-2025-009",
    address: "Secretariat Complex, Alausa, Ikeja",
    note: "Health inspection report submission",
    fromTitle: "Health Department",
    date: "2025-06-09",
    attachments: ["/attachments/health-report.jpg"],
  },
  {
    toTitle: "Uniform Supplier",
    referenceNo: "PD-2025-010",
    address: "45, Commercial Road, Apapa",
    note: "Order for school uniforms",
    fromTitle: "Procurement",
    date: "2025-06-10",
    attachments: ["/attachments/uniform-order.jpg"],
  },
  {
    toTitle: "Security Agency",
    referenceNo: "PD-2025-011",
    address: "Zone 4, Wuse, Abuja",
    note: "Request for enhanced school security",
    fromTitle: "Admin",
    date: "2025-06-11",
    attachments: ["/attachments/security-request.jpg"],
  },
  {
    toTitle: "Educational Consultant",
    referenceNo: "PD-2025-012",
    address: "6, Isaac John Street, Ikeja GRA",
    note: "Proposal for school improvement program",
    fromTitle: "Principal's Office",
    date: "2025-06-12",
    attachments: ["/attachments/school-proposal.jpg"],
  },
  {
    toTitle: "Local Government Council",
    referenceNo: "PD-2025-013",
    address: "Local Government Secretariat, Badagry",
    note: "Notification of school facility maintenance",
    fromTitle: "Facilities",
    date: "2025-06-13",
    attachments: ["/attachments/maintenance.jpg"],
  },
  {
    toTitle: "Nigerian Red Cross",
    referenceNo: "PD-2025-014",
    address: "Red Cross Crescent, Ebute Metta",
    note: "Request for first aid training",
    fromTitle: "Health Unit",
    date: "2025-06-14",
    attachments: ["/attachments/first-aid.jpg"],
  },
  {
    toTitle: "PTA Treasurer",
    referenceNo: "PD-2025-015",
    address: "PTA Office, School Premises",
    note: "Submission of PTA annual financial report",
    fromTitle: "Accounts Department",
    date: "2025-06-15",
    attachments: ["/attachments/pta-report.jpg"],
  },
  {
    toTitle: "Ministry of Education",
    referenceNo: "PD-2025-016",
    address: "Education House, Alausa, Ikeja",
    note: "Application for school grant support",
    fromTitle: "Principal's Office",
    date: "2025-06-16",
    attachments: ["/attachments/grant-application.jpg"],
  },
  {
    toTitle: "Librarian, Public Library",
    referenceNo: "PD-2025-017",
    address: "Library Road, Yaba",
    note: "Donation of old library books",
    fromTitle: "Library Unit",
    date: "2025-06-17",
    attachments: ["/attachments/book-donation.jpg"],
  },
  {
    toTitle: "National Youth Service Corps (NYSC)",
    referenceNo: "PD-2025-018",
    address: "NYSC Secretariat, Surulere",
    note: "Request for posting of NYSC teachers",
    fromTitle: "HR Department",
    date: "2025-06-18",
    attachments: ["/attachments/nysc-request.jpg"],
  },
  {
    toTitle: "Engineering Contractors Ltd.",
    referenceNo: "PD-2025-019",
    address: "Construction Village, Lekki",
    note: "Request for quotation for laboratory renovation",
    fromTitle: "Facility Management",
    date: "2025-06-19",
    attachments: ["/attachments/lab-quote.jpg"],
  },
  {
    toTitle: "Registrar, WAEC Office",
    referenceNo: "PD-2025-020",
    address: "WAEC Building, Yaba, Lagos",
    note: "Final reminder on registration deadline",
    fromTitle: "Academic Affairs",
    date: "2025-06-20",
    attachments: ["/attachments/registration.jpg"],
  },
];

export const postalReceiveData = [
  {
    fromTitle: "Ministry of Education",
    referenceNo: "PR-2025-001",
    address: "Secretariat Complex, Alausa, Ikeja",
    note: "Approval of school improvement grant",
    toTitle: "Principal, Pascal College",
    date: "2025-06-01",
    attachments: ["/attachments/grant_approval_letter.jpg"],
  },
  {
    fromTitle: "PTA Secretary",
    referenceNo: "PR-2025-002",
    address: "PTA Office, School Premises",
    note: "Minutes of last PTA meeting",
    toTitle: "Admin Office",
    date: "2025-06-02",
    attachments: ["/attachments/pta_minutes.jpg"],
  },
  {
    fromTitle: "WAEC Office",
    referenceNo: "PR-2025-003",
    address: "WAEC Headquarters, Yaba, Lagos",
    note: "Examination registration confirmation",
    toTitle: "Exams Office",
    date: "2025-06-03",
    attachments: ["/attachments/registration_confirmation.jpg"],
  },
  {
    fromTitle: "Public Library",
    referenceNo: "PR-2025-004",
    address: "Library Street, Yaba",
    note: "Acknowledgement of donated books",
    toTitle: "Library Unit",
    date: "2025-06-04",
    attachments: ["/attachments/donation_acknowledgement.jpg"],
  },
  {
    fromTitle: "Book Suppliers Ltd.",
    referenceNo: "PR-2025-005",
    address: "5, Ajah Industrial Estate, Lekki",
    note: "Quotation for textbook order",
    toTitle: "Procurement Unit",
    date: "2025-06-05",
    attachments: ["/attachments/book_quotation.jpg"],
  },
  {
    fromTitle: "ICT Support Company",
    referenceNo: "PR-2025-006",
    address: "Tech Park, Abuja",
    note: "Solution report for server downtime",
    toTitle: "ICT Department",
    date: "2025-06-06",
    attachments: ["/attachments/server_solution_report.jpg"],
  },
  {
    fromTitle: "Sports Equipment Ltd.",
    referenceNo: "PR-2025-007",
    address: "Ikoyi, Lagos",
    note: "Response to sports kits quotation",
    toTitle: "Sports Unit",
    date: "2025-06-07",
    attachments: ["/attachments/sports_response.jpg"],
  },
  {
    fromTitle: "Health Inspection Unit",
    referenceNo: "PR-2025-008",
    address: "Ministry of Health, Lagos",
    note: "Feedback on school health inspection",
    toTitle: "Health Department",
    date: "2025-06-08",
    attachments: ["/attachments/health_feedback.jpg"],
  },
  {
    fromTitle: "Cleaning Services Co.",
    referenceNo: "PR-2025-009",
    address: "Awolowo Way, Ikeja",
    note: "Signed contract renewal document",
    toTitle: "Facility Management",
    date: "2025-06-09",
    attachments: ["/attachments/contract_signed.jpg"],
  },
  {
    fromTitle: "Educational Consultant",
    referenceNo: "PR-2025-010",
    address: "Ikeja GRA",
    note: "Response to school improvement proposal",
    toTitle: "Principal",
    date: "2025-06-10",
    attachments: ["/attachments/proposal_response.jpg"],
  },
  {
    fromTitle: "Security Agency",
    referenceNo: "PR-2025-011",
    address: "Zone 4, Abuja",
    note: "Acknowledgement of security request",
    toTitle: "Admin",
    date: "2025-06-11",
    attachments: ["/attachments/security_acknowledgement.jpg"],
  },
  {
    fromTitle: "NYSC Secretariat",
    referenceNo: "PR-2025-012",
    address: "NYSC Office, Surulere",
    note: "Posting confirmation of NYSC teachers",
    toTitle: "HR Department",
    date: "2025-06-12",
    attachments: ["/attachments/nysc_posting_confirmation.jpg"],
  },
  {
    fromTitle: "Engineering Contractors Ltd.",
    referenceNo: "PR-2025-013",
    address: "Lekki, Lagos",
    note: "Quotation for laboratory renovation",
    toTitle: "Facilities",
    date: "2025-06-13",
    attachments: ["/attachments/lab_renovation_quotation.jpg"],
  },
  {
    fromTitle: "Red Cross",
    referenceNo: "PR-2025-014",
    address: "Ebute Metta, Lagos",
    note: "Acceptance of first aid training request",
    toTitle: "Health Unit",
    date: "2025-06-14",
    attachments: ["/attachments/first_aid_training_acceptance.jpg"],
  },
  {
    fromTitle: "PTA Treasurer",
    referenceNo: "PR-2025-015",
    address: "PTA Office, School Premises",
    note: "Receipt of annual financial report",
    toTitle: "Accounts Department",
    date: "2025-06-15",
    attachments: ["/attachments/financial_report_receipt.jpg"],
  },
  {
    fromTitle: "Local Government",
    referenceNo: "PR-2025-016",
    address: "Badagry Secretariat",
    note: "Approval for school facility maintenance",
    toTitle: "Principal's Office",
    date: "2025-06-16",
    attachments: ["/attachments/maintenance_approval.jpg"],
  },
  {
    fromTitle: "Book Suppliers Ltd.",
    referenceNo: "PR-2025-017",
    address: "Ajah Industrial Estate",
    note: "Delivery note for ordered textbooks",
    toTitle: "Procurement Unit",
    date: "2025-06-17",
    attachments: ["/attachments/textbook_delivery_note.jpg"],
  },
  {
    fromTitle: "Ministry of Education",
    referenceNo: "PR-2025-018",
    address: "Alausa Secretariat",
    note: "Remittance of school grant fund",
    toTitle: "Accounts Department",
    date: "2025-06-18",
    attachments: ["/attachments/grant_fund_remittance.jpg"],
  },
  {
    fromTitle: "PTA Chairman",
    referenceNo: "PR-2025-019",
    address: "PTA Office",
    note: "Suggestion letter for new school facilities",
    toTitle: "Principal",
    date: "2025-06-19",
    attachments: ["/attachments/pta_suggestion_letter.jpg"],
  },
  {
    fromTitle: "WAEC Office",
    referenceNo: "PR-2025-020",
    address: "WAEC, Yaba",
    note: "Final notification on registration deadline",
    toTitle: "Exams Office",
    date: "2025-06-20",
    attachments: ["/attachments/registration_deadline_notice.jpg"],
  },
];

export const admissionEnquiryData = [
  {
    name: "Mr. Adewale Johnson",
    phone: "+2348012345678",
    email: "adewale.johnson@example.com",
    address: "12, Ogunlana Drive, Surulere, Lagos",
    description: "Enquiring about admission process for his child",
    note: "Interested in scholarship options",
    date: "2025-06-01",
    nextFollowUpDate: "2025-06-05",
    assignedStaff: "Mrs. Adebayo",
    reference: "parent",
    source: "facebook",
    class: "Primary 3",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Chinyere Okafor",
    phone: "+2348023456789",
    email: "chinyere.okafor@example.com",
    address: "5, Nnamdi Azikiwe Crescent, Abuja",
    description: "Admission for two children transferring from another school",
    note: "Needs hostel accommodation",
    date: "2025-06-02",
    nextFollowUpDate: "2025-06-06",
    assignedStaff: "Mr. Bello",
    reference: "partner",
    source: "whatsapp",
    class: "JSS2",
    numberOfChild: 2,
  },
  {
    name: "Mr. Samuel Eze",
    phone: "+2348034567890",
    email: "samuel.eze@example.com",
    address: "32, Ozumba Mbadiwe, Victoria Island, Lagos",
    description: "Inquiry for SS1 science class enrollment",
    note: "Wants science laboratory tour",
    date: "2025-06-03",
    nextFollowUpDate: "2025-06-07",
    assignedStaff: "Mrs. Uche",
    reference: "staff",
    source: "ads",
    class: "SS1",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Bukola Aina",
    phone: "+2348045678901",
    email: "bukola.aina@example.com",
    address: "9, Alausa Close, Ikeja",
    description: "Requesting fee structure for multiple children",
    note: "Follow-up on discounts for siblings",
    date: "2025-06-04",
    nextFollowUpDate: "2025-06-10",
    assignedStaff: "Mr. Bello",
    reference: "parent",
    source: "platform",
    class: "Primary 5",
    numberOfChild: 3,
  },
  {
    name: "Mr. Tunde Ajayi",
    phone: "+2348056789012",
    email: "tunde.ajayi@example.com",
    address: "15, Airport Road, Benin City",
    description: "Admission for child with special needs",
    note: "Requested meeting with school counselor",
    date: "2025-06-05",
    nextFollowUpDate: "2025-06-08",
    assignedStaff: "Mrs. Hassan",
    reference: "partner",
    source: "whatsapp",
    class: "Primary 2",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Funke Balogun",
    phone: "+2348067890123",
    email: "funke.balogun@example.com",
    address: "27, Allen Avenue, Ikeja, Lagos",
    description: "Interested in after-school programs",
    note: "Wants visit scheduled for next week",
    date: "2025-06-06",
    nextFollowUpDate: "2025-06-12",
    assignedStaff: "Mr. Bello",
    reference: "staff",
    source: "facebook",
    class: "Primary 4",
    numberOfChild: 1,
  },
  {
    name: "Mr. James Emmanuel",
    phone: "+2348078901234",
    email: "james.emmanuel@example.com",
    address: "18, Ring Road, Ibadan",
    description: "Asking about entrance exam dates",
    note: "Requested syllabus for preparation",
    date: "2025-06-07",
    nextFollowUpDate: "2025-06-09",
    assignedStaff: "Mrs. Adebayo",
    reference: "parent",
    source: "ads",
    class: "JSS1",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Zainab Usman",
    phone: "+2348089012345",
    email: "zainab.usman@example.com",
    address: "Plot 10, Maitama, Abuja",
    description: "Relocation from UK, interested in SS2",
    note: "Asked about boarding school facilities",
    date: "2025-06-08",
    nextFollowUpDate: "2025-06-15",
    assignedStaff: "Mr. Bello",
    reference: "partner",
    source: "platform",
    class: "SS2",
    numberOfChild: 1,
  },
  {
    name: "Mr. Seyi Ogunleye",
    phone: "+2348090123456",
    email: "seyi.ogunleye@example.com",
    address: "3, Herbert Macaulay Way, Yaba",
    description: "Enquiring for Primary 1 admission next term",
    note: "Requested early registration form",
    date: "2025-06-09",
    nextFollowUpDate: "2025-06-12",
    assignedStaff: "Mrs. Hassan",
    reference: "student",
    source: "facebook",
    class: "Primary 1",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Amaka Obi",
    phone: "+2348101234567",
    email: "amaka.obi@example.com",
    address: "Ajah, Lagos",
    description: "Request for details about SS3 WAEC preparation",
    note: "Asked for testimonial from past students",
    date: "2025-06-10",
    nextFollowUpDate: "2025-06-14",
    assignedStaff: "Mrs. Uche",
    reference: "staff",
    source: "ads",
    class: "SS3",
    numberOfChild: 1,
  },
  {
    name: "Mr. Abdulrahman Musa",
    phone: "+2348112345678",
    email: "abdul.musa@example.com",
    address: "Kaduna North, Kaduna",
    description: "Interested in JSS1 for two children",
    note: "Prefers remote virtual meeting",
    date: "2025-06-11",
    nextFollowUpDate: "2025-06-17",
    assignedStaff: "Mrs. Hassan",
    reference: "parent",
    source: "whatsapp",
    class: "JSS1",
    numberOfChild: 2,
  },
  {
    name: "Mrs. Helen Eyo",
    phone: "+2348123456789",
    email: "helen.eyo@example.com",
    address: "Eket, Akwa Ibom",
    description: "Asking about scholarships for brilliant students",
    note: "Follow up required by principal",
    date: "2025-06-12",
    nextFollowUpDate: "2025-06-18",
    assignedStaff: "Mr. Bello",
    reference: "partner",
    source: "facebook",
    class: "Primary 6",
    numberOfChild: 1,
  },
  {
    name: "Mr. Ugochukwu Nnaji",
    phone: "+2348134567890",
    email: "ugo.nnaji@example.com",
    address: "Onitsha, Anambra",
    description: "Wants to confirm availability of science subjects",
    note: "Requested school brochure",
    date: "2025-06-13",
    nextFollowUpDate: "2025-06-19",
    assignedStaff: "Mrs. Uche",
    reference: "staff",
    source: "platform",
    class: "SS1",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Grace Akanbi",
    phone: "+2348145678901",
    email: "grace.akanbi@example.com",
    address: "Ibadan South, Ibadan",
    description: "Needs guidance on registration documents",
    note: "Waiting for principal’s feedback",
    date: "2025-06-14",
    nextFollowUpDate: "2025-06-20",
    assignedStaff: "Mrs. Hassan",
    reference: "parent",
    source: "ads",
    class: "JSS3",
    numberOfChild: 1,
  },
  {
    name: "Mr. Richard Daniels",
    phone: "+2348156789012",
    email: "richard.daniels@example.com",
    address: "Port Harcourt, Rivers",
    description: "Interested in Junior Secondary entrance exams",
    note: "Asked for full fee schedule",
    date: "2025-06-15",
    nextFollowUpDate: "2025-06-22",
    assignedStaff: "Mr. Bello",
    reference: "partner",
    source: "whatsapp",
    class: "JSS1",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Rukayat Bello",
    phone: "+2348167890123",
    email: "rukayat.bello@example.com",
    address: "Sango Ota, Ogun",
    description: "Enquiry for nursery school sibling admission",
    note: "Requested meeting with head teacher",
    date: "2025-06-16",
    nextFollowUpDate: "2025-06-23",
    assignedStaff: "Mrs. Hassan",
    reference: "parent",
    source: "platform",
    class: "Primary 1",
    numberOfChild: 2,
  },
  {
    name: "Mr. Ibrahim Yusuf",
    phone: "+2348178901234",
    email: "ibrahim.yusuf@example.com",
    address: "Zaria, Kaduna",
    description: "Asking for details about school transport services",
    note: "Waiting for school bus route map",
    date: "2025-06-17",
    nextFollowUpDate: "2025-06-24",
    assignedStaff: "Mr. Bello",
    reference: "staff",
    source: "facebook",
    class: "Primary 2",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Janet Okonkwo",
    phone: "+2348189012345",
    email: "janet.okonkwo@example.com",
    address: "Aba, Abia State",
    description: "Admission inquiry for twins",
    note: "Requested separate rooms in boarding",
    date: "2025-06-18",
    nextFollowUpDate: "2025-06-25",
    assignedStaff: "Mrs. Uche",
    reference: "parent",
    source: "whatsapp",
    class: "Primary 3",
    numberOfChild: 2,
  },
  {
    name: "Mr. Femi Alabi",
    phone: "+2348190123456",
    email: "femi.alabi@example.com",
    address: "Ile Ife, Osun",
    description: "Interested in summer school programs",
    note: "Requested early registration for summer",
    date: "2025-06-19",
    nextFollowUpDate: "2025-06-27",
    assignedStaff: "Mrs. Hassan",
    reference: "partner",
    source: "ads",
    class: "Primary 5",
    numberOfChild: 1,
  },
  {
    name: "Mrs. Ngozi Ibe",
    phone: "+2348201234567",
    email: "ngozi.ibe@example.com",
    address: "Owerri, Imo State",
    description: "Wants update on child’s previous application",
    note: "Requested callback by admission officer",
    date: "2025-06-20",
    nextFollowUpDate: "2025-06-28",
    assignedStaff: "Mr. Bello",
    reference: "student",
    source: "platform",
    class: "Primary 6",
    numberOfChild: 1,
  },
];

export const complaintsData = [
  {
    complaintType: "fees",
    source: "whatsapp",
    complainBy: "Mrs. Amina Lawal",
    phone: "+2348012345678",
    date: "2025-06-01",
    description: "Overcharged for PTA fees.",
    actionTaken: "Investigation ongoing.",
    assigned: "Mr. Musa Ahmed",
    note: "Receipts requested for verification.",
    attachDocument: ["pta_fee_receipt.pdf"],
  },
  {
    complaintType: "hostel",
    source: "facebook",
    complainBy: "Mr. Chuka Okoye",
    phone: "+2348023456789",
    date: "2025-06-02",
    description: "Poor water supply in hostel block B.",
    actionTaken: "Maintenance informed.",
    assigned: "Mrs. Gloria Eze",
    note: "To be resolved within 3 days.",
    attachDocument: ["photo_of_hostel_leak.jpg"],
  },
  {
    complaintType: "feeding",
    source: "ads",
    complainBy: "Mrs. Funke Ayeni",
    phone: "+2348034567890",
    date: "2025-06-03",
    description: "Food served to students is cold.",
    actionTaken: "Kitchen staff warned.",
    assigned: "Mr. Peter Onah",
    note: "Monitor food service quality.",
    attachDocument: [],
  },
  {
    complaintType: "fees",
    source: "whatsapp",
    complainBy: "Mr. Ahmed Sule",
    phone: "+2348045678901",
    date: "2025-06-04",
    description: "Transport fee unclear.",
    actionTaken: "Breakdown provided.",
    assigned: "Mrs. Dorcas Adamu",
    note: "Parent satisfied.",
    attachDocument: ["transport_breakdown.pdf"],
  },
  {
    complaintType: "hostel",
    source: "ads",
    complainBy: "Mrs. Sarah Obi",
    phone: "+2348056789012",
    date: "2025-06-05",
    description: "Lighting problem in hostel corridor.",
    actionTaken: "Electrician called.",
    assigned: "Mr. John Adeyemi",
    note: "To be fixed by next week.",
    attachDocument: ["hostel_corridor_photo.jpg"],
  },
  {
    complaintType: "feeding",
    source: "facebook",
    complainBy: "Mr. Felix Igwe",
    phone: "+2348067890123",
    date: "2025-06-06",
    description: "Students served expired snacks.",
    actionTaken: "Supplier suspended.",
    assigned: "Mrs. Anita Bassey",
    note: "Food safety training planned.",
    attachDocument: ["expired_snacks_photo.jpg"],
  },
  {
    complaintType: "fees",
    source: "ads",
    complainBy: "Mr. Bashir Ibrahim",
    phone: "+2348078901234",
    date: "2025-06-07",
    description: "Double deduction of fees.",
    actionTaken: "Refund initiated.",
    assigned: "Mr. Daniel Okoro",
    note: "To confirm refund by next week.",
    attachDocument: ["bank_statement.pdf"],
  },
  {
    complaintType: "hostel",
    source: "whatsapp",
    complainBy: "Mrs. Chinwe Eke",
    phone: "+2348089012345",
    date: "2025-06-08",
    description: "Mosquito infestation.",
    actionTaken: "Fumigation scheduled.",
    assigned: "Mrs. Victoria Adebayo",
    note: "Inform students ahead.",
    attachDocument: [],
  },
  {
    complaintType: "feeding",
    source: "facebook",
    complainBy: "Mr. Gideon Akpan",
    phone: "+2348090123456",
    date: "2025-06-09",
    description: "Students allergic to peanut-based meals.",
    actionTaken: "Menu revised.",
    assigned: "Mr. Sunday Ogundele",
    note: "Special diet provided.",
    attachDocument: ["allergy_report.pdf"],
  },
  {
    complaintType: "fees",
    source: "whatsapp",
    complainBy: "Mrs. Kemi Afolabi",
    phone: "+2348101234567",
    date: "2025-06-10",
    description: "Late fee penalty unclear.",
    actionTaken: "Clarified via PTA platform.",
    assigned: "Mrs. Beatrice Eze",
    note: "Parents briefed in last meeting.",
    attachDocument: [],
  },
  {
    complaintType: "hostel",
    source: "ads",
    complainBy: "Mr. Joseph Enang",
    phone: "+2348112345678",
    date: "2025-06-11",
    description: "Broken bed frames in hostel.",
    actionTaken: "Replacements ordered.",
    assigned: "Mr. Hassan Sule",
    note: "Delivery expected soon.",
    attachDocument: ["broken_bed_photo.jpg"],
  },
  {
    complaintType: "feeding",
    source: "facebook",
    complainBy: "Mrs. Ngozi Udoh",
    phone: "+2348123456789",
    date: "2025-06-12",
    description: "Quantity of food served is small.",
    actionTaken: "Portion size increased.",
    assigned: "Mr. Samuel Musa",
    note: "Monitor for next two weeks.",
    attachDocument: [],
  },
  {
    complaintType: "fees",
    source: "whatsapp",
    complainBy: "Mrs. Fatima Suleiman",
    phone: "+2348134567890",
    date: "2025-06-13",
    description: "Overdue balance conflict.",
    actionTaken: "Account reconciled.",
    assigned: "Mrs. Adunni Ajayi",
    note: "Confirmed balance to parent.",
    attachDocument: ["payment_receipt.jpg"],
  },
  {
    complaintType: "hostel",
    source: "ads",
    complainBy: "Mr. Seyi Bello",
    phone: "+2348145678901",
    date: "2025-06-14",
    description: "Broken windows in hostel rooms.",
    actionTaken: "Immediate repair ordered.",
    assigned: "Mr. Lucky Etim",
    note: "Ensure proper safety.",
    attachDocument: ["broken_window_photo.jpg"],
  },
  {
    complaintType: "feeding",
    source: "facebook",
    complainBy: "Mrs. Halima Danjuma",
    phone: "+2348156789012",
    date: "2025-06-15",
    description: "Lack of vegetables in student meals.",
    actionTaken: "Menu balanced.",
    assigned: "Mrs. Florence Ajibola",
    note: "Monitor kitchen compliance.",
    attachDocument: [],
  },
  {
    complaintType: "fees",
    source: "whatsapp",
    complainBy: "Mr. John Olaniyi",
    phone: "+2348167890123",
    date: "2025-06-16",
    description: "Payment not reflecting in school records.",
    actionTaken: "System updated.",
    assigned: "Mrs. Ruth Chukwu",
    note: "IT to ensure regular sync.",
    attachDocument: ["transaction_slip.pdf"],
  },
  {
    complaintType: "hostel",
    source: "ads",
    complainBy: "Mrs. Jennifer Uka",
    phone: "+2348178901234",
    date: "2025-06-17",
    description: "Leaking ceiling in hostel bathroom.",
    actionTaken: "Roof repairs ongoing.",
    assigned: "Mr. Henry Okon",
    note: "Fencing to prevent hazard.",
    attachDocument: ["ceiling_leak.jpg"],
  },
  {
    complaintType: "feeding",
    source: "facebook",
    complainBy: "Mr. Lawal Babatunde",
    phone: "+2348189012345",
    date: "2025-06-18",
    description: "Juice expired before consumption.",
    actionTaken: "Supplier notified.",
    assigned: "Mrs. Amaka Obi",
    note: "Change beverage supplier.",
    attachDocument: ["juice_expiry_label.jpg"],
  },
  {
    complaintType: "fees",
    source: "whatsapp",
    complainBy: "Mrs. Grace Ejiro",
    phone: "+2348190123456",
    date: "2025-06-19",
    description: "Inconsistent fees for siblings.",
    actionTaken: "Discount applied.",
    assigned: "Mr. Emeka Nwosu",
    note: "Policy to be reviewed by finance.",
    attachDocument: [],
  },
  {
    complaintType: "hostel",
    source: "ads",
    complainBy: "Mr. Collins Adewale",
    phone: "+2348201234567",
    date: "2025-06-20",
    description: "No proper cleaning of hostel toilets.",
    actionTaken: "Hygiene inspection routine intensified.",
    assigned: "Mrs. Yetunde Olufemi",
    note: "Weekly cleaning report submission enforced.",
    attachDocument: ["toilet_condition_photo.jpg"],
  },
];

export const purposesData = [
  { purpose: "Student Meeting", description: "Meeting with students regarding academic matters" },
  { purpose: "PTA", description: "Parent-Teacher Association general meeting" },
  { purpose: "Staff Meeting", description: "Internal staff planning or administrative meeting" },
  { purpose: "Vendor Meeting", description: "Meeting with external service providers" },
  { purpose: "Consultation", description: "Academic or counseling consultation with staff" },
  { purpose: "Admission Enquiry", description: "Parents visiting to inquire about admissions" },
];

export const complaintsTypeData = [
  { complaint: "Fees", description: "Issues related to school fees, payments, discounts, or refunds" },
  { complaint: "Hostel", description: "Concerns about hostel facilities, maintenance, or management" },
  { complaint: "Feeding", description: "Complaints regarding the food quality, quantity, or menu" },
  { complaint: "Transport", description: "Complaints about transportation, delays, or costs" },
  { complaint: "Academics", description: "Concerns regarding teaching or curriculum" },
];

export const sourcesData = [
  { source: "Ads", description: "Came through online or offline advertisements" },
  { source: "Facebook", description: "Contacted via Facebook campaigns or posts" },
  { source: "Whatsapp", description: "Contacted or referred via WhatsApp communication" },
  { source: "Website", description: "Inquiry made through the official school website" },
  { source: "Flyers", description: "Got information via physical flyers or banners" },
  { source: "Referrals", description: "Recommended by existing students, parents, or staff" },
];

export const referencesData = [
  { reference: "Staff", description: "Referred or associated with a staff member" },
  { reference: "Parent", description: "Associated with a current student's parent" },
  { reference: "Student", description: "Directly related to an existing or former student" },
  { reference: "Partner School", description: "Recommended by a partner school or institution" },
  { reference: "Alumni", description: "Referred by school alumni or graduates" },
];












export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// Updated to show events starting from 06/06/2025
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 5, 6, 8, 0),
    end: new Date(2025, 5, 6, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 5, 6, 9, 0),
    end: new Date(2025, 5, 6, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 5, 6, 10, 0),
    end: new Date(2025, 5, 6, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 5, 6, 11, 0),
    end: new Date(2025, 5, 6, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 5, 6, 13, 0),
    end: new Date(2025, 5, 6, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 5, 6, 14, 0),
    end: new Date(2025, 5, 6, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 5, 9, 9, 0),
    end: new Date(2025, 5, 9, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 5, 9, 10, 0),
    end: new Date(2025, 5, 9, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 5, 9, 11, 0),
    end: new Date(2025, 5, 9, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 5, 9, 14, 0),
    end: new Date(2025, 5, 9, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 5, 10, 8, 0),
    end: new Date(2025, 5, 10, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 5, 10, 10, 0),
    end: new Date(2025, 5, 10, 10, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 5, 10, 13, 0),
    end: new Date(2025, 5, 10, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 5, 10, 14, 0),
    end: new Date(2025, 5, 10, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 5, 11, 9, 0),
    end: new Date(2025, 5, 11, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 5, 11, 10, 0),
    end: new Date(2025, 5, 11, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 5, 11, 11, 0),
    end: new Date(2025, 5, 11, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 5, 11, 14, 0),
    end: new Date(2025, 5, 11, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 5, 12, 8, 0),
    end: new Date(2025, 5, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 5, 12, 9, 0),
    end: new Date(2025, 5, 12, 9, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 5, 12, 11, 0),
    end: new Date(2025, 5, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 5, 12, 13, 0),
    end: new Date(2025, 5, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 5, 12, 14, 0),
    end: new Date(2025, 5, 12, 14, 45),
  },
];
