const academicDropdownItems = [
  { name: "Facilities", href: "/academics/facilities" },
  { name: "Annual Sports Day", href: "/academics/sports-day" },
  { name: "Course", href: "/academics/course" },
  { name: "School Uniform", href: "/academics/uniform" },
  { name: "Principal Message", href: "/academics/principal-message" },
  { name: "School Management", href: "/academics/management" },
  { name: "Know Us", href: "/academics/know-us" },
  { name: "Approach", href: "/academics/approach" },
  { name: "Pre Primary", href: "/academics/pre-primary" },
  { name: "Teacher", href: "/academics/teachers" },
  { name: "Houses & Mentoring", href: "/academics/houses" },
  { name: "Student Council", href: "/academics/student-council" },
  { name: "Career Counselling", href: "/academics/counselling" },
];

const navItems = [
  { name: "Home", href: "/" },
  { name: "Online Course", href: "/online-course" },
  { name: "Online Admission", href: "/online-admission" },
  { name: "Cbse Exam Result", href: "/cbse-result" },
  { name: "Exam Result", href: "/exam-result" },
  { name: "Annual Calendar", href: "/calendar" },
  { name: "About Us", href: "/about" },
  { name: "Academics", href: "#" },
  { name: "Gallery", href: "/gallery" },
  { name: "Events", href: "/events" },
  { name: "News", href: "/news" },
  { name: "Contact", href: "/contact" },
];